const courses = [
  "Mechatronics Engineering W/S in Robotics Nanotechnology",
  "Mechatronics Engineering (Industrial IoT and Systems Engineering)",
  "Mechatronics Engineering (Immersive Technologies)",
  "Mechatronics Engineering (Autonomous Driving Technology)",
  "Mechatronics Engineering",
  "Mechanical Engineering W/S in Artificial Intelligence and Machine Learning",
  "Mechanical Engineering (Automation and Robotics)",
  "Mechanical Engineering",
  "Electronics Engineering (VLSI Design and Technology)",
  "Electronics and Instrumentation Engineering",
  "Electronics and Computer Engineering",
  "Electronics and Communication Engineering W/S in Cyber Physical Systems",
  "Electronic and Communication Engineering W/S in Data Science",
  "Electrical and Electronics Engineering",
  "Electric Vehicle Technology",
  "Computer Science and Engineering W/S in Software Engineering",
  "Computer Science and Engineering W/S in Internet of Things (IOT)",
  "Computer Science and Engineering W/S in Information Technology",
  "Computer Science and Engineering W/S in Gaming Technology",
  "Computer Science and Engineering W/S in Cyber Security",
  "Computer Science and Engineering W/S in Computer Networking",
  "Computer Science and Engineering W/S in Cloud Computing",
  "Computer Science and Engineering W/S in Block chain Technology",
  "Computer Science and Engineering W/S in Big Data Analytics",
  "Computer Science and Engineering W/S in Artificial Intelligence and Machine Learning",
  "Computer Science and Engineering (Data Science)",
  "Computer Science and Engineering",
  "Computer Science and Business System (in partnership with TCS)",
  "Civil Engineering with Computer Applications",
  "Civil Engineering",
  "Chemical Engineering",
  "Biotechnology W/S in Regenerative Medicine",
  "Biotechnology W/S in Genetic Engineering",
  "Biotechnology W/S in Food Technology",
  "Biotechnology (Computational Biology)",
  "Biotechnology",
  "Biomedical Engineering W/S in Machine Intelligence",
  "Biomedical Engineering (BME)",
  "Automotive Engineering (ARAI, Pune)",
  "Automobile Engineering W/S in Vehicles Testing (GARC)",
  "Automobile Engineering W/S in Automotive Electronics",
  "Automobile Engineering Automation and Robotics",
  "Artificial Intelligence",
  "Aerospace Engineering",
];

module.exports = courses;
